name: Deploy branch to staging

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script:
            cd mystash-backend
            git pull
            echo -e "$(date)\n$(cat .push-history)" > .push-history
            pm2 restart ./src/index.js
