name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies (root + frontend)
        run: npm install
      - name: Build shared package
        working-directory: packages/shared
        run: npm run build
      - name: Run frontend tests
        working-directory: packages/frontend
        run: npm test
        env:
          CI: true

  backend:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies (root + backend)
        run: npm install
      - name: Build shared package
        working-directory: packages/shared
        run: npm run build
      - name: Run backend tests
        working-directory: packages/backend
        run: npm test
        env:
          CI: true

  e2e:
    name: E2E Playwright Tests
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies (root + e2e)
        run: npm install
      - name: Build shared package
        working-directory: packages/shared
        run: npm run build

      - name: Make backend setup script executable
        working-directory: packages/backend
        run: chmod +x setup-dev-backend.sh
      - name: Prepare backend services
        working-directory: packages/backend
        run: ./setup-dev-backend.sh
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
      - name: Start serverless offline
        working-directory: packages/backend
        run: |
          nohup npx serverless offline start &
        env:
          MYSTASH_SECRET: ${{ secrets.MYSTASH_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          GITHUB_REDIRECT_URI: ${{ secrets.GITHUB_REDIRECT_URI }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Start frontend in background
        working-directory: packages/frontend
        run: |
          nohup npm start > frontend.log 2>&1 &

      - name: Wait for frontend and backend to be ready
        run: sleep 15

      - name: Run e2e tests
        working-directory: packages/e2e
        run: npm test
        env:
          CI: true
      - name: Upload Playwright test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: packages/e2e/test-results/
