name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Change to your Node.js version

      - name: Install dependencies for frontend
        working-directory: packages/frontend
        run: npm install

      - name: Run frontend tests
        working-directory: packages/frontend
        run: npm test
        env:
          CI: true

      - name: Install dependencies for backend
        working-directory: packages/backend
        run: npm install
        env:
          CI: true

      - name: Run backend tests
        working-directory: packages/backend
        run: npm test
